import { fmt, fmtPct, gainClass } from "~/composables/useCalculations";

const STOCK_CLASS = () =>
  "font-mono font-bold text-indigo-600 dark:text-indigo-400 tracking-wider text-xs uppercase";

// ── TableWithModal column display configs ──────────────────────────────────
export const COLUMNS = {
  openPositions: [
    {
      field: "stock",
      header: "Stock",
      minW: "min-w-28",
      frozen: true,
      alignFrozen: "left",
      isStock: true,
      editorType: "text",
    },
    {
      field: "stockExchange",
      header: "Exchange",
      minW: "min-w-24",
      editorType: "select",
      options: ["NSE", "BSE"],
    },
    {
      field: "buyDate",
      header: "Buy Date",
      minW: "min-w-32",
      editorType: "date",
    },
    {
      field: "buyPrice",
      header: "Buy Price",
      minW: "min-w-28",
      format: fmt,
      editorType: "decimal",
    },
    { field: "qty", header: "Qty", minW: "min-w-20", editorType: "number" },
    { field: "buyValue", header: "Buy Value", minW: "min-w-28", format: fmt },
    {
      field: "cmp",
      header: "CMP",
      minW: "min-w-28",
      format: fmt,
      editorType: "decimal",
    },
    {
      field: "peakPrice",
      header: "Peak",
      minW: "min-w-28",
      format: fmt,
      editorType: "decimal",
    },
    {
      field: "dropFromPeak",
      header: "Drop%",
      minW: "min-w-24",
      format: fmtPct,
      bodyClass: (n) =>
        n > 20 ? "text-red-500 dark:text-red-400 font-medium" : "",
    },
    {
      field: "currentValue",
      header: "Curr Value",
      minW: "min-w-28",
      format: fmt,
    },
    {
      field: "pctGain",
      header: "% Gain",
      minW: "min-w-24",
      format: fmtPct,
      bodyClass: gainClass,
    },
    {
      field: "annualGainPct",
      header: "Annual%",
      minW: "min-w-24",
      format: fmtPct,
      bodyClass: gainClass,
    },
    { field: "days", header: "Days", minW: "min-w-20" },
    {
      field: "strategyName",
      header: "Strategy",
      minW: "min-w-36",
      editorType: "text",
    },
    {
      field: "targetPrice",
      header: "Target",
      minW: "min-w-28",
      format: fmt,
      editorType: "decimal",
    },
    {
      field: "totalPotentialGain",
      header: "Total Pot%",
      minW: "min-w-28",
      format: fmtPct,
    },
    {
      field: "remainingGain",
      header: "Remaining%",
      minW: "min-w-28",
      format: fmtPct,
    },
    {
      field: "targetValue",
      header: "Target Val",
      minW: "min-w-28",
      format: fmt,
    },
    {
      field: "description",
      header: "Description",
      minW: "min-w-40",
      editorType: "text",
    },
  ],
  closedPositions: [
    {
      field: "stock",
      header: "Stock",
      minW: "min-w-28",
      frozen: true,
      alignFrozen: "left",
      isStock: true,
      editorType: "text",
    },
    {
      field: "buyDate",
      header: "Buy Date",
      minW: "min-w-32",
      editorType: "date",
    },
    {
      field: "buyRate",
      header: "Buy Rate",
      minW: "min-w-28",
      format: fmt,
      editorType: "decimal",
    },
    { field: "qty", header: "Qty", minW: "min-w-20", editorType: "number" },
    { field: "buyValue", header: "Buy Value", minW: "min-w-28", format: fmt },
    {
      field: "sellDate",
      header: "Sell Date",
      minW: "min-w-32",
      editorType: "date",
    },
    {
      field: "sellPrice",
      header: "Sell Price",
      minW: "min-w-28",
      format: fmt,
      editorType: "decimal",
    },
    { field: "sellValue", header: "Sell Value", minW: "min-w-28", format: fmt },
    {
      field: "gain",
      header: "Gain",
      minW: "min-w-28",
      format: fmt,
      bodyClass: gainClass,
    },
    { field: "days", header: "Days", minW: "min-w-20" },
    {
      field: "pctGain",
      header: "% Gain",
      minW: "min-w-24",
      format: fmtPct,
      bodyClass: gainClass,
    },
    {
      field: "annualGainPct",
      header: "Annual%",
      minW: "min-w-24",
      format: fmtPct,
      bodyClass: gainClass,
    },
    {
      field: "description",
      header: "Description",
      minW: "min-w-40",
      editorType: "text",
    },
  ],
  etfs: [
    { key: "type", label: "Type" },
    { key: "stock", label: "Stock", frozen: true, class: STOCK_CLASS },
    { key: "stockExchange", label: "Exchange" },
    { key: "buyDate", label: "Buy Date" },
    { key: "buyPrice", label: "Buy Price", format: fmt },
    { key: "qty", label: "Qty" },
    { key: "buyValue", label: "Buy Value", format: fmt },
    { key: "cmp", label: "CMP", format: fmt },
    { key: "currentValue", label: "Curr Value", format: fmt },
    {
      key: "pctGain",
      label: "% Gain",
      format: fmtPct,
      class: (r) => gainClass(r.pctGain),
    },
    { key: "days", label: "Days" },
    { key: "target", label: "Target", format: fmt },
  ],
  closedEtfs: [
    { key: "type", label: "Type" },
    { key: "stock", label: "Stock", frozen: true, class: STOCK_CLASS },
    { key: "buyDate", label: "Buy Date" },
    { key: "buyRate", label: "Buy Rate", format: fmt },
    { key: "qty", label: "Qty" },
    { key: "buyValue", label: "Buy Value", format: fmt },
    { key: "sellDate", label: "Sell Date" },
    { key: "sellPrice", label: "Sell Price", format: fmt },
    { key: "sellValue", label: "Sell Value", format: fmt },
    {
      key: "gain",
      label: "Gain",
      format: fmt,
      class: (r) => gainClass(r.gain),
    },
    { key: "days", label: "Days" },
    {
      key: "pctGain",
      label: "% Gain",
      format: fmtPct,
      class: (r) => gainClass(r.pctGain),
    },
    {
      key: "annualGainPct",
      label: "Annual%",
      format: fmtPct,
      class: (r) => gainClass(r.annualGainPct),
    },
  ],
  commodityEtfs: [
    { key: "type", label: "Type" },
    { key: "stock", label: "Stock", frozen: true, class: STOCK_CLASS },
    { key: "stockExchange", label: "Exchange" },
    { key: "buyDate", label: "Buy Date" },
    { key: "buyPrice", label: "Buy Price", format: fmt },
    { key: "qty", label: "Qty" },
    { key: "buyValue", label: "Buy Value", format: fmt },
    { key: "cmp", label: "CMP", format: fmt },
    { key: "currentValue", label: "Curr Value", format: fmt },
    {
      key: "pctGain",
      label: "% Gain",
      format: fmtPct,
      class: (r) => gainClass(r.pctGain),
    },
    { key: "days", label: "Days" },
  ],
  closedCommodityEtfs: [
    { key: "stock", label: "Stock", frozen: true, class: STOCK_CLASS },
    { key: "buyDate", label: "Buy Date" },
    { key: "buyRate", label: "Buy Rate", format: fmt },
    { key: "qty", label: "Qty" },
    { key: "buyValue", label: "Buy Value", format: fmt },
    { key: "sellDate", label: "Sell Date" },
    { key: "sellPrice", label: "Sell Price", format: fmt },
    { key: "sellValue", label: "Sell Value", format: fmt },
    {
      key: "gain",
      label: "Gain",
      format: fmt,
      class: (r) => gainClass(r.gain),
    },
    { key: "days", label: "Days" },
    {
      key: "pctGain",
      label: "% Gain",
      format: fmtPct,
      class: (r) => gainClass(r.pctGain),
    },
    {
      key: "annualGainPct",
      label: "Annual%",
      format: fmtPct,
      class: (r) => gainClass(r.annualGainPct),
    },
  ],
  cagrEntries: [
    { key: "text", label: "Description", frozen: true },
    { key: "date", label: "Date" },
    { key: "amount", label: "Amount", format: fmt },
    { key: "investmentOrOut", label: "Type" },
  ],
  commodityCagrEntries: [
    { key: "text", label: "Description", frozen: true },
    { key: "date", label: "Date" },
    { key: "amount", label: "Amount", format: fmt },
  ],
};

// ── TableWithModal form field configs ──────────────────────────────────────
export const FIELD_CONFIGS = {
  etfs: [
    { key: "type", label: "Type" },
    { key: "stock", label: "Stock Symbol" },
    {
      key: "stockExchange",
      label: "Exchange",
      type: "select",
      options: ["NSE", "BSE"],
    },
    { key: "buyDate", label: "Buy Date", type: "date" },
    { key: "buyPrice", label: "Buy Price", type: "number" },
    { key: "qty", label: "Qty", type: "number" },
    { key: "cmp", label: "CMP", type: "number" },
    { key: "target", label: "Target", type: "number" },
  ],
  closedEtfs: [
    { key: "type", label: "Type" },
    { key: "stock", label: "Stock Symbol" },
    { key: "buyDate", label: "Buy Date", type: "date" },
    { key: "buyRate", label: "Buy Rate", type: "number" },
    { key: "qty", label: "Qty", type: "number" },
    { key: "sellDate", label: "Sell Date", type: "date" },
    { key: "sellPrice", label: "Sell Price", type: "number" },
  ],
  commodityEtfs: [
    { key: "type", label: "Type" },
    { key: "stock", label: "Stock Symbol" },
    {
      key: "stockExchange",
      label: "Exchange",
      type: "select",
      options: ["NSE", "BSE"],
    },
    { key: "buyDate", label: "Buy Date", type: "date" },
    { key: "buyPrice", label: "Buy Price", type: "number" },
    { key: "qty", label: "Qty", type: "number" },
    { key: "cmp", label: "CMP", type: "number" },
  ],
  closedCommodityEtfs: [
    { key: "stock", label: "Stock Symbol" },
    { key: "buyDate", label: "Buy Date", type: "date" },
    { key: "buyRate", label: "Buy Rate", type: "number" },
    { key: "qty", label: "Qty", type: "number" },
    { key: "sellDate", label: "Sell Date", type: "date" },
    { key: "sellPrice", label: "Sell Price", type: "number" },
  ],
  cagrEntries: [
    { key: "text", label: "Description" },
    { key: "date", label: "Date", type: "date" },
    { key: "amount", label: "Amount", type: "number" },
    {
      key: "investmentOrOut",
      label: "Type",
      type: "select",
      options: ["Investment", "Out"],
    },
  ],
  commodityCagrEntries: [
    { key: "text", label: "Description" },
    { key: "date", label: "Date", type: "date" },
    { key: "amount", label: "Amount", type: "number" },
  ],
};

// ── TableWithModal blank row templates ─────────────────────────────────────
export const BLANK_ROWS = {
  etfs: {
    type: "",
    stock: "",
    stockExchange: "NSE",
    buyDate: "",
    buyPrice: 0,
    qty: 0,
    cmp: 0,
    target: 0,
  },
  closedEtfs: {
    type: "",
    stock: "",
    buyDate: "",
    buyRate: 0,
    qty: 0,
    sellDate: "",
    sellPrice: 0,
  },
  commodityEtfs: {
    type: "",
    stock: "",
    stockExchange: "NSE",
    buyDate: "",
    buyPrice: 0,
    qty: 0,
    cmp: 0,
  },
  closedCommodityEtfs: {
    stock: "",
    buyDate: "",
    buyRate: 0,
    qty: 0,
    sellDate: "",
    sellPrice: 0,
  },
  cagrEntries: { text: "", date: "", amount: 0, investmentOrOut: "Investment" },
  commodityCagrEntries: { text: "", date: "", amount: 0 },
};
